#===================================================================
#
#   Setup the environment properly
#
#===================================================================
INC     = d:\WATCOM\h;d:\WATCOM\h\os2;.;..\;d:\ddk\include

!ifndef %RELEASE
#DBGFLG   = -dDEBUG=1
DBGFLG = 
!endif
MODFLG = -dTEXTMODE -dDEBUG
SRCDIR = ..\

#===================================================================
#
#   Auto-dependency information
#
#===================================================================
.ERASE
.SUFFIXES:
.SUFFIXES: .lst .obj .c .asm

CFLAGS  = $(MODFLG) -w4 -e25 -otexan -d2 -bm -ez -mf -i$(INC) -5r -bt=os2 -zq
CC      = WPP386 $(CFLAGS)

AFLAGS  = -q
ASM     = WASM $(AFLAGS)

DFLAGS  = -l -s
DIS     = WDISASM $(DFLAGS)

#LFLAGS  = sys os2v2 pm op m d all op st=16384 op c op maxe=25 op q op symf
LFLAGS   = sys os2v2 op m d all op st=131072 op maxe=25 op q op symf
QFLAGS  = system os2 dll option quiet, map, align=512
LINK    = WLINK $(LFLAGS)

BFLAGS  = -s -t -c -b -q -n
LIB     = WLIB $(BFLAGS)

.obj.lst:
        $(DIS) $*

.c.obj: .AUTODEPEND
        $(CC) $*.c

.asm.obj: .AUTODEPEND
        $(ASM) $*.asm

#===================================================================
#
#   List of source files
#
#===================================================================
FILE0   = record.obj dart.obj \gus\asm\lib\mmpm2.lib
FILE2   = 
FILE3   = 
FILE4   = 
FILE5   = 
FILE6   = 
FILE7   = 
FILE8   = 
FILE9   = 
FILES   = $(FILE0) $(FILE1) $(FILE2) $(FILE3) $(FILE4) $(FILE5) $(FILE6) $(FILE7) $(FILE8) $(FILE9)
TARGET  = record



#===================================================================
#
#   Specific dependencies
#
#===================================================================
all: $(TARGET).EXE

$(TARGET).lnk: makefile
    @%write $^@ name $(TARGET).EXE
    @for %f in ($(FILES)) do @%append $^@ file %f

$(TARGET).exe: $(TARGET).lnk $(FILES)
    $(LINK) @$(TARGET).lnk
